version: '3.3'
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=dbunit
      - POSTGRES_PASSWORD=dbunit
      - POSTGRES_DB=dbunit
    ports:
      - 5432:5432
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=dbunit
      - MYSQL_USER=dbunit
      - MYSQL_PASSWORD=dbunit
      - MYSQL_ROOT_PASSWORD=dbunit
      - TZ="America/Chicago"
    ports:
      - 3306:3306
  mssql:
    image: dbunit/dbunit-it-sqlserver:2.0.0
    ports:
      - 1433:1433
  mssql2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_HOST=sqlserver19
      - MSSQL_SA_PASSWORD=theSaPassword1234
      - SA_PASSWORD=theSaPassword1234

      - DB_HOST=sqlserver19
      - DB_DATABASE=dbunit
      - DB_USERNAME=sa
      - DB_PASSWORD=theSaPassword1234
    ports:
      - 1433:1433
  oracle11:
    image: dbunit/dbunit-it-oracle11g:1.0.1
    ports:
      - 1521:1521